### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/modulo-3-evaluacion-intermedia-Beatrizsobri#1]
Buen trabajo @Beatrizsobri  !

### Algunas pistas para acabarlo:

- [x] Usa propTypes para comprobar el tipo de dato de las props
- [x] Revisa los metadatos en index.html (lang, title...)
- [x] Usa el estado para guardar los datos
- [x] Este debería llamarse `apiData` https://github.com/Adalab/modulo-3-evaluacion-intermedia-Beatrizsobri/blob/master/src/components/App.js#L5 ya que no es una clase de JS.

### Cuando tengas esto puedes:

1. Añadir un click a Pokemon que: marca o desmarca el pokemon como favorito en el array del estado de App.
1. Pasar este dato al componente Pokemon por props
1. Pintar Pokemon con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

Si tienes cualquier duda, avisa!

Al turrón!!!

**Comment by Beatrizsobri** [comment]
@migueldelmazo Corregida!
